### ISSUE TITLE
clean up output, and consider own output generator

### ISSUE THREAD

**Issue by sevko** [pelias/acceptance-tests#8]
This issue consists of two closely-related parts. Firstly, the test output is excessively noisy:

```javascript

> pelias-acceptance-tests@0.0.0 test /home/sevko/src/mapzen/acceptance-tests
> mocha -R spec tests



  GET /search

    1) [id:0] query: { input: 'brooklyn' } (top 3)

    2) [id:1] query: { input: 'brooklyn, ny' } (top 3)

    3) [id:2] query: { input: 'new york' } (top 3)

    4) [id:3] query: { input: 'philadelphia' } (top 3)

    5) [id:4] query: { input: 'new york, ny' } (top 3)

    6) [id:5] query: { input: '130 dean street brooklyn, ny' } (top 1)

    ✓ [id:6] query: { input: 'billerica' } (top 1) (54ms)

    ✓ [id:7] query: { input: 'billerica, ma' } (top 1) (90ms)

    7) [id:8] query: { input: '15 call street billerica, ma' } (top 1)

    8) [id:9] query: { input: 'union sq' } (top 3)

    9) [id:10] query: { input: 'union square' } (top 1)

    ✓ [id:11] query: { input: 'portland' } (top 1) (59ms)

    ✓ [id:12] query: { input: 'paris' } (top 1) (73ms)

    10) [id:13] query: { input: 'france' } (top 3)

    11) [id:14] query: { input: 'prospect park' } (top 1)

    ✓ [id:15] query: { input: 'london' } (top 1) (57ms)


  5 passing (7s)
  11 failing

  1) GET /search [id:0] query: { input: 'brooklyn' } (top 3):
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

  2) GET /search [id:1] query: { input: 'brooklyn, ny' } (top 3):
     Error: Expected result not in top 3
      at Object.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/tests/searchTest.js:81:19)
      at Test.assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:221:6)
      at assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:132:12)
      at /home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:129:5
      at Test.Request.callback (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:746:30)
      at Test.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)

  3) GET /search [id:2] query: { input: 'new york' } (top 3):
     Error: Expected result not in top 3
      at Object.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/tests/searchTest.js:81:19)
      at Test.assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:221:6)
      at assert (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:132:12)
      at /home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/lib/test.js:129:5
      at Test.Request.callback (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:746:30)
      at Test.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/supertest/node_modules/superagent/lib/node/index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16
      at process._tickCallback (node.js:419:13)

  4) GET /search [id:3] query: { input: 'philadelphia' } (top 3):
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/home/sevko/src/mapzen/acceptance-tests/node_modules/mocha/lib/runnable.js:159:19)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

/* etc */
```

The stack traces at the end make it difficult to view the failing tests at the top of the output, and there's some additional text in those (like the time the query took) that might not be worth displaying. I think the traces should definitely go, and while we remove them, we should consider just writing our own output generator here instead of using **mocha**. Could look something like this:

```
✘ [id 9] 'brooklyn': timeout of 2000ms exceeded
✘ [id 9] 'new york, ny': not in top 10 results
✘ [id 9] 'new york, ny': not in top 10 results
✓ [id 10] 'union sq': no `out` object specified
✓ [id 10] 'union square'
```

I'm suggesting that since it'll give us fine-tuned control over the output format in the long run, and would remove auto-injected mocha text.

**Comment by sevko** [comment]
cc @hkrishna , @dianashk .

**Comment by dianashk** [comment]
I agree. It's noisy and mocha isn't buying us much here.
I'd be fine with simplifying and making it just report in a format we like.

Ultimately, we want to generate a report file (json/csv/?), publish it somewhere and/or email to pelias@mapzen.com. The goal is to be able to compare latest result with the previous ones and report what has changed (and maybe even have informative charts over time).

**Comment by sevko** [comment]
Perfect, I'll work on it and suggest some output formats.

**Comment by sevko** [comment]
Trying to classify the types of failures. Here's what I've got:

  * a `null` `out` was specified, meaning this test is a placeholder (**fail**)
  * a `string` `out` was specified but a match couldn't be found in `test_cases/locations.json`. Also a placeholder (**fail**)
  * no match was found in the API results at all (**fail**)
  * a match *was* found in the results, but not inside the `priorityThresh` (**fail**)
  * a match was found in the results, in the expected `priorityThresh` (**success**)

I'm thinking there'll be a function that collects the results from each test-case, and then other functions that format it into terminal output, an email, etc.

**Comment by dianashk** [comment]
There is one more type of failure that I'd like to have show up as pending and not fail.

```javascript
{
  id: 10,
  in: { input: 'something' },
  out: 'missing data'
}
```
```
✘ [id 9] 'new york, ny': not in top 10 results
! [id 10] 'something': missing data
✓ [id 11] 'union square'
```
